server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:dmitrii-demchenko/spring-boot-configs.git
          username: username
          password: password
          default-label: main
          search-paths: "{application}"